name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'
      id: java
      
    - name: Set up Android emulator
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 30
        arch: x86_64
        profile: Nexus 5X
        emulator-options: -no-window
      id: emulator
      
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Build with Gradle
      run: ./gradlew build
      
    - name: Run unit tests with Gradle
      run: ./gradlew test
      
    - name: Run instrumented tests with Gradle
      run: ./gradlew connectedCheck
      env:
        EMULATOR_SERIAL_PORT: ${{ steps.emulator.outputs.serial-port }}
        ADB_INSTALL_TIMEOUT: 10
